### ISSUE TITLE
possible collaboration 

### ISSUE THREAD

**Issue by parthp08** [b4sgren/rigidTransformation#1]
Hello, i just saw your repo and i was thinking of writing similar library in cpp for transformations. so would you like to discuss this project in brief. i would very much like to contribute if you dont mind.

**Comment by b4sgren** [comment]
That's fine. I'm open to collaboration. I'm mostly finished with a python library that does the same thing so part of my goal with this library was to learn a little more about templating and inheritance in C++

**Comment by parthp08** [comment]
okay, i also have library in python, but wanted to do it in cpp to learning purposes.
